language: android
dist: trusty

android:
  components:
    - build-tools-29.0.0
    - android-29
    - extra

before_install:
  - chmod +x gradlew

script:
  - "./gradlew assembleRelease"
  - "mv app/build/outputs/apk/app-release-unsigned.apk app/build/outputs/apk/XposedVizpowerHook.apk"

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: "app/build/outputs/apk/app-release-unsigned.apk"
  skip_cleanup: true
  on:
    tags: true
    repo: lyc8503/VizpowerHook